### ISSUE TITLE
after run demo.bat or demo-hubble.bat, there is error

### ISSUE THREAD

**Issue by AlbertG123** [GameTechDev/SamplerFeedbackStreaming#3]
I build SamplerFeedbackStreaming.sln by VS2019. I download release1 and Hubble-16k.zip , then put them at C:\hubble-16k folder.
I run demo.bat or demo-hubble.bat, there will be an error :
C:\hubble-16k\200-m51-whirlpool.xet incorrect XET version. 

can you help check why? 
and after run " expense.exe -mediadir C:\hubble-16k " , there is also an error returned.

**Comment by allenhux-intel** [comment]
Near the top of Readme.md, I mention there was a change to the XeT file format. You can modify convert.bat to filter on .xet and perform a conversion of the whole directory from the old to the new format.

**Comment by allenhux-intel** [comment]
I recently checked in a change to convert.bat so it enumerates .xet files in addition to dds files. Try "convert.bat c:\hubble-16k c:\hubble-16k-v2", it should convert all the files to the new format.

**Comment by allenhux-intel** [comment]
Easiest solution: put the hubble xet files in the dds directory and re-build DdsToXet. They will be converted and placed in the target directory media folder. closing bug.
