### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by PonBao** [GameTechDev/SamplerFeedbackStreaming#4]
Can someone help to check why I always build solution with Error

Error Code : MSB3073	
The command "cd /d C:\Users\Precision 22000\Desktop\SamplerFeedbackStreaming-main\x64\Release\
convert.bat C:\Users\Precision 22000\Desktop\SamplerFeedbackStreaming-main\dds media
:VCEnd" exited with code 1.

Project : DdsToXet

File : C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets

LINE : 157

**Comment by allenhux-intel** [comment]
Try moving "SamplerFeedbackStreaming-main" to e.g. c:\

If that works, you may be able to guess what's wrong, and submit a pull request with a fix to the batch file.

**Comment by allenhux-intel** [comment]
Checked in fix for source directory containing spaces resulting in failure of post-build step in DdsToXet.
